### ISSUE TITLE
osascript is not allowed to send keystrokes

### ISSUE THREAD

**Issue by ianjsikes** [jozanza/p8#2]
When I make a change to my lua file and the build auto-reloads, it throws an error running the applescript to send Cmd+R to PICO-8. The error message is:
```
execution error: System Events got an error: osascript is not allowed to send keystrokes.
```
I tried adding `osascript` **and** `p8` under System Preferences > Privacy > Accessibility, but no luck. Is there some other thing required to give the script the right permissions?

**Comment by jozanza** [comment]
Hey thanks for reporting!

@ianjsikes can you describe the steps you are going through to produce this error? I wasn't able to make this happen on High Sierra or Mojave (10.14.2).

However, one thing I did notice was, on Mojave, a prompt popped up after I ran `p8 start --watch` command:

<img width="422" alt="Screen Shot 2019-04-13 at 12 29 03 AM" src="https://user-images.githubusercontent.com/740794/56074602-77971600-5d83-11e9-8deb-30c60879f249.png">

I hit "OK", and the prompt hasn't shown up again. Is it possible you received such a prompt and maybe hit "Don't Allow" instead? If so, I'm not certain, but you may need to give the shell you are using to run `p8` sufficient privileges to control "System Events".

**Comment by ianjsikes** [comment]
I don't think I ever got that popup. I added my terminal in accessibility settings. I'm going to close this though, because it randomly started working a few days later. ¯\\\_(ツ)\_/¯

**Comment by henrikstroem** [comment]
You must give Terminal permission to control the computer. That worked for me.

![Screenshot 2020-04-15 at 08 51 17](https://user-images.githubusercontent.com/907338/79307043-8b290f80-7ef6-11ea-80ca-483165e97f26.png)

**Comment by wangliangster** [comment]
follow all refered, seems ok! but recover again soon, manually give accessibility to Terminal you need, cycler.... don't touch the root cause!
